# Generated by Django 5.2.11 on 2026-02-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_otp_profile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
